services:
  audiocleaner:
    image: audiocleaner-audiocleaner:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${AUDIOCLEANER_HOSTNAME}
    hostname: ${AUDIOCLEANER_HOSTNAME}
    user: "${PUID}:${PGID}"
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "${AUDIOCLEANER_PORT}:9830"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
      - ./work:/app/work
      - ${RESOURCE}/Media:/media
