# Jellyfin - 媒体服务器
# 端口说明：
#   - 8096: HTTP Web 访问端口

services:
  jellyfin:
    extends:
      file: ${NVIDIA_GPU_TEMPLATE}
      service: nvidia-runtime
    image: "jellyfin/jellyfin:latest"
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    ports:
      - "${JELLYFIN_PORT}:8096"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      HTTP_PROXY: ${PROXY_HTTP}
      HTTPS_PROXY: ${PROXY_HTTPS}
      NO_PROXY: ${NO_PROXY}
    volumes:
      - ${LOCALTIME_PATH}:/etc/localtime:ro
      - ${FONT}:/usr/share/fonts
      - ${COMPOSE_DATA_PATH}/scripts:/scripts
      - ${RESOURCE}/Media:/media
      - ./cache:/cache 
      - ./config:/config
